### ISSUE TITLE
资源管理器卡死

### ISSUE THREAD

**Issue by Arvinsyt** [VirtualHotBar/NetMount#11]
1.0.4版本挂载webdav磁盘以只读的方式，无论是选择桌面还是自动分配盘符，点击一个视频然后右键就会卡死。选择自动分配盘符挂载并卸载后，盘符也不会立即消失，而是必须退出软件，资源管理器重启才会消失；选择桌面挂载并卸载则正常会立即消失

**Comment by VirtualHotBar** [comment]
检查网络环境及缓存配置
