### ISSUE TITLE
开机自启功能不管用

### ISSUE THREAD

**Issue by niustark** [VirtualHotBar/NetMount#12]
1.04版本
win11系统
每次保存了配置 开机自启
下次打开还是未勾选状态

**Comment by VirtualHotBar** [comment]
安装包的后缀是exe还是msi？

**Comment by niustark** [comment]
> 安装包的后缀是exe还是msi？

NetMount_1.0.4_x64-setup.exe
CRC32: 085C0507
MD5: E7DFED57D4C4913EA817BBF1B670EF0C
SHA-1: 91535AD49AEC9BA5DBF7DC321FB4AF045CEF0BC6

**Comment by zy19941113** [comment]
同样问题。exe的

**Comment by niustark** [comment]
> 同样问题。exe的

1.06还是存在这个问题

**Comment by VirtualHotBar** [comment]
@niustark @zy19941113 
新版应该修复了(v1.1)
