### ISSUE TITLE
能否不添加存储直接挂载webdav

### ISSUE THREAD

**Issue by p1aintiff** [VirtualHotBar/NetMount#14]
服务器以搭建alist，可以直接挂载；
不太清楚alist后台占资源用会不会影响游戏；

**Comment by p1aintiff** [comment]
还有一个问题：
似乎只能在挂载储存之间创建任务，但是没有发现挂载本地存储

**Comment by lidawei97688** [comment]
我是在服务器用sftpgo搭建的webdav，也是只需要直接挂载就行
