### ISSUE TITLE
挂载网盘缓存默认在C盘,能不能添加能修改缓存目录位置

### ISSUE THREAD

**Issue by fbh45** [VirtualHotBar/NetMount#15]

**Comment by jiayihello** [comment]
同问

**Comment by Huiaei** [comment]
+1

**Comment by VirtualHotBar** [comment]
已实现：
https://github.com/VirtualHotBar/NetMount/commit/1bd4e105df5a420761ef4c0df936214f91396b80
https://github.com/VirtualHotBar/NetMount/commit/46040659772b3a773a13285f5bef0fcea8ad4399
