### ISSUE TITLE
直接讀取已有的rclone存儲？

### ISSUE THREAD

**Issue by Yusei-StarDust** [VirtualHotBar/NetMount#19]
開發者您好，目前使用上有一些疑問想請教一下：
1. 是否能直接讀取現有的rclone存儲，而不用重新添加？
2. 掛載時如何指定分配磁碟代號(盤符)？

**Comment by VirtualHotBar** [comment]
关于第2点，挂载路径选择自定义，输入目标盘符即可：
![image](https://github.com/VirtualHotBar/NetMount/assets/96966978/87824577-1102-40a8-a876-2f702202af04)

**Comment by VirtualHotBar** [comment]
move to https://github.com/VirtualHotBar/NetMount/issues/10
