### ISSUE TITLE
修改 AListV3 驱动器中的磁盘总容量后报错

### ISSUE THREAD

**Issue by SAFEluren** [VirtualHotBar/NetMount#2]
如图，填写任意大于-1的数值报错
`Error:HTTP 400 - Bad Request key "vfsOpt": Reshape failed to Unmarshal: json: cannot unmarshal object into Go struct field Options.CacheMode of type int64`
![image](https://github.com/VirtualHotBar/NetMount/assets/79032826/8c31c24f-6835-4c75-b587-cca4c0d2f248)

**Comment by VirtualHotBar** [comment]
已修复:https://github.com/VirtualHotBar/NetMount/commit/5e989bca4ba8492c3dfe5a74b04637b544563dfd
等待软件更新
