### ISSUE TITLE
希望支持linux命令行

### ISSUE THREAD

**Issue by ypq123456789** [VirtualHotBar/NetMount#21]
是这样的，目前是只能用桌面端，windows家宽口子太小，传输速度太慢，满速上传久了还会被当做pcdn封杀（南京移动直接封到1.5MB/s且一上传切换到高延迟线路）。
支持linux命令行的话，等于就是结合了rclone和alist的优势。现在rclone的问题就是基本不支持alist支持的众多国内网盘，这导致必须通过alist webdav套娃的方式来挂载国内网盘比如阿里云盘等，一方面，套娃本身就有问题，例如rclone以为自己上传完毕了，其实只是传输到alist了，alist其实还在调用网盘的api慢慢上传，容易导致出错和反复上传；另一方面，webdav部分网盘（例如阿里云盘）不支持传输文件的创建和修改时间，这导致文件传输过去后显示的修改时间是上传时间，即使在rclone里面添加参数--no-update-modtime --size-only ，还是会出现反复上传的问题。
如果rclone能够原生支持alist支持的众多网盘，那么就是完美的了，这些问题就迎刃而解。这个项目感觉很适合做这个，毕竟桌面端目前确实就是alist和rclone的缝合哈哈。

**Comment by VirtualHotBar** [comment]
https://docs.netmount.cn/docs/qa#%E4%B8%BA%E4%BB%80%E4%B9%88%E6%B2%A1%E6%9C%89%E5%AE%B9%E5%99%A8docker%E7%89%88%E6%9C%AC

**Comment by VirtualHotBar** [comment]
上述问题本项目也无法解决，因为本项目也是通过alist webdav套娃的方式
