### ISSUE TITLE
I worked on Build on Windows. However...

### ISSUE THREAD

**Issue by SingingDalong** [VirtualHotBar/NetMount#22]
![2024-06-04_053829](https://github.com/VirtualHotBar/NetMount/assets/25282693/22eaf3a6-7d75-42ab-a83f-9142daf918ea)
I worked on Build on Windows. However, when you run NetMount.exe, a command prompt window also opens. What should I modify to get rid of this command prompt window?

**Comment by VirtualHotBar** [comment]
已修复:https://github.com/VirtualHotBar/NetMount/commit/2a02c9e2715ae1384f7726ced81d314136755711

**Comment by SingingDalong** [comment]
> 已修复:[2a02c9e](https://github.com/VirtualHotBar/NetMount/commit/2a02c9e2715ae1384f7726ced81d314136755711)
谢谢。效果很好。
