### ISSUE TITLE
windows11闪退

### ISSUE THREAD

**Issue by hyy34** [VirtualHotBar/NetMount#23]
版本	Windows 11 企业版
版本	22H2
安装日期	‎2023/‎1/‎3
操作系统版本	22621.3593

下载官网的NetMount_1.1.0_x64-setup.exe 以及 Github的NetMount_1.1.0_x64_zh-CN.msi
安装后，桌面图标打开，程序闪退。。

请问能是什么问题？

**Comment by Jackxwb** [comment]
Window 10 官网下载的exe同闪退。
首次打开白屏，任务管理器强制退出后，手动打开 app.exe 就闪退

---

下载源代码

使用 `pnpm tauri-dev` 运行，有报错，无法运行
```
pnpm tauri-dev

> netmount-gui@1.1.1 tauri-dev D:\Soft\File\远程文件挂载、同步\NetMount\src\NetMount
> tauri dev

    Error failed to get cargo metadata: program not found
 ELIFECYCLE  Command failed with exit code 1.
```

使用 `pnpm run dev` 运行，浏览器控制台有报错
```
window.js:85  Uncaught TypeError: Cannot read properties of undefined (reading 'metadata')
    at getCurrent (window.js:85:50)
    at getCurrent2 (webview.js:28:24)
    at Object.getCurrent3 (webviewWindow.js:15:21)
    at window.ts:6:35
```

**Comment by VirtualHotBar** [comment]
已修复:https://github.com/VirtualHotBar/NetMount/commit/b3e53fd9788ff011ff0df54ba7e34e6a22bb5f8c

**Comment by Jackxwb** [comment]
> 已修复:[b3e53fd](https://github.com/VirtualHotBar/NetMount/commit/b3e53fd9788ff011ff0df54ba7e34e6a22bb5f8c)

好像把 `app.exe`，重命名为 `NetMount.exe` 就能正常运行了
![image](https://github.com/VirtualHotBar/NetMount/assets/34720403/c96b623e-7e69-4ea3-bbcf-750e9de86fa5)
