### ISSUE TITLE
任务栏右键关闭无法最小化并出错

### ISSUE THREAD

**Issue by hyy34** [VirtualHotBar/NetMount#25]
版本 Windows 11 企业版
版本 22H2
安装日期 ‎2023/‎1/‎3
操作系统版本 22621.3593

V1.1.1版本，点右上角的X可以最小化，但是在任务栏右键点击关闭，会出现Devtools界面，然后出现错误，需要程序退出重新启动。
具体视频见附件。

但是问题其实不太影响使用。

https://github.com/VirtualHotBar/NetMount/assets/26433019/9a49893e-7521-4306-8e72-537b639e1007

**Comment by VirtualHotBar** [comment]
已修复:https://github.com/VirtualHotBar/NetMount/commit/898565679665b4e56bb57c40f303996cfc408b07

**Comment by hyy34** [comment]
跟下个版本一起发布被？

**Comment by VirtualHotBar** [comment]
是的，下个发布版本修复
