### ISSUE TITLE
[BUG]云存储挂载到本地文件，资源管理器打开部分文件夹的速度很慢，甚至会卡死

### ISSUE THREAD

**Issue by 1625123930** [VirtualHotBar/NetMount#31]
就像这样

![屏幕截图 2024-06-12 084242](https://github.com/VirtualHotBar/NetMount/assets/88610573/38fe4474-7a51-45f4-926d-b43e30058778)

而通过raidrive挂载则速度正常可以做到秒开

![屏幕截图 2024-06-12 085144](https://github.com/VirtualHotBar/NetMount/assets/88610573/5f481a29-704e-4f47-aeba-ce25fc13393a)

**Comment by 1625123930** [comment]
补充一点，在浏览这里速度正常的，立马就可以显示文件夹内的文件
![屏幕截图 2024-06-12 090359](https://github.com/VirtualHotBar/NetMount/assets/88610573/da116577-0504-488b-bd8b-be7589862843)

**Comment by VirtualHotBar** [comment]
检查网络环境或预览及缓存设置

**Comment by 3054528216** [comment]
> 检查网络环境或预览及缓存设置

预览缓存设置有文档吗,我这打开视频得一个视频全部加载完才能看
