### ISSUE TITLE
在ArchLinux启动时出现 23654 segmentation fault (core dumped)

### ISSUE THREAD

**Issue by postyizhan** [VirtualHotBar/NetMount#33]
![图片](https://github.com/VirtualHotBar/NetMount/assets/97342038/809b6b66-9611-4567-abd0-e21be9cbd5ff)
![图片](https://github.com/VirtualHotBar/NetMount/assets/97342038/f08d6fc4-5907-4603-87c0-c785414e4302)

**Comment by ArcticLampyrid** [comment]
试试 AUR：https://aur.archlinux.org/packages/netmount
