### ISSUE TITLE
[问题] 官网显示支持 cloudflare，但是软件里似乎并没有找到

### ISSUE THREAD

**Issue by bling-yshs** [VirtualHotBar/NetMount#44]
如题
![image](https://github.com/user-attachments/assets/e84b9b1e-cd1c-4048-8932-aacbc2377188)
![image](https://github.com/user-attachments/assets/60df4bb0-d27a-4f9d-a424-780bde728066)

**Comment by VirtualHotBar** [comment]
r2不是支持s3么😅
