### ISSUE TITLE
[Question]双向同步任务似乎无效

### ISSUE THREAD

**Issue by CreeperAWA** [VirtualHotBar/NetMount#46]
我添加了几个双向同步任务，有运行的记录，但似乎并没有同步任何东西，手动触发也不行
这是我填写的内容，请问是否应该是这样？（我确认我填写的路径没有错误）
![image](https://github.com/user-attachments/assets/5a492e0a-8053-4a7c-9676-f9328f8109ce)

**Comment by VirtualHotBar** [comment]
rclone日志看看

**Comment by CreeperAWA** [comment]
`2024/07/27 20:35:52 ERROR : rc: "sync/bisync": error: Didn't find key "path1" in input`

**Comment by VirtualHotBar** [comment]
已修复：https://github.com/VirtualHotBar/NetMount/commit/5668b129ef6f2e0b9735390efd93cbf055707ef0
