### ISSUE TITLE
x86 running on mac reports CPU type error

### ISSUE THREAD

**Issue by zgswq** [VirtualHotBar/NetMount#7]
dmg name：NetMount_1.0.3_x64
---
Operation steps:
1. Download the dmg file
2. Double-click to open the dmg file
3. Double-click to install netmount
---
Error：Bad CPU type in executable (os error 86)

**Comment by VirtualHotBar** [comment]
https://github.com/VirtualHotBar/NetMount/commit/f63670586d737e27104487ac80c21e3b21cff67b

**Comment by VirtualHotBar** [comment]
已修复：https://github.com/VirtualHotBar/NetMount/releases/tag/v1.0.4
在mac上使用需要安装一个依赖:macfuse
