### ISSUE TITLE
挂载为本地盘后，直接在盘内执行部分exe安装包报错该如何解决？

### ISSUE THREAD

**Issue by shinobiz** [VirtualHotBar/NetMount#77]
![QQ截图20241116211240](https://github.com/user-attachments/assets/845149f6-35b5-46e3-9ea9-ee17f69c478b)
把盘挂载为网络盘就没事

**Comment by VirtualHotBar** [comment]
https://docs.netmount.cn/docs/storage-mount#%E8%A1%A5%E5%85%85
